import { create } from '@storybook/theming/create';

export const customThemes = {
  lightblue: create({
    base: 'light',
    brandTitle: 'Mon Design System',
    brandUrl: 'https://example.com',
    brandImage: '',
    
    appBg: '#F0F8FF',
    appContentBg: '#FFFFFF',
    appBorderColor: '#DDDDFF',
    appBorderRadius: 6,
    fontBase: '"Open Sans", sans-serif',
    fontCode: 'monospace',
    textColor: '#333333',
    textInverseColor: '#FFFFFF',
    barTextColor: '#333333',
    barSelectedColor: '#0066CC',
    barBg: '#E6F0FF',
    inputBg: '#FFFFFF',
    inputBorder: '#CCCCFF',
    inputTextColor: '#333333',
    inputBorderRadius: 4,
    colorPrimary: '#0066CC',
    colorSecondary: '#7B9CFF',
    }),
    
    darkblue: create({
    base: 'dark',
    brandTitle: 'Mon Design System',
    brandUrl: 'https://example.com',
    brandImage: '',
    appBg: '#0A1929',
    appContentBg: '#101E2C',
    appBorderColor: '#1E3A5F',
    appBorderRadius: 6,
    fontBase: '"Open Sans", sans-serif',
    fontCode: 'monospace',
    textColor: '#E0E0E0',
    textInverseColor: '#101E2C',
    barTextColor: '#E0E0E0',
    barSelectedColor: '#7B9CFF',
    barBg: '#0A1929',
    inputBg: '#1A2B3D',
    inputBorder: '#1E3A5F',
    inputTextColor: '#E0E0E0',
    inputBorderRadius: 4,
    colorPrimary: '#7B9CFF',
    colorSecondary: '#4D76CC',
    }),
    
    lightgreen: create({
    base: 'light',
    appBg: '#F0FFF0',
    appContentBg: '#FFFFFF',
    appBorderColor: '#CCFFCC',
    appBorderRadius: 6,
    fontBase: '"Open Sans", sans-serif',
    fontCode: 'monospace',
    textColor: '#333333',
    textInverseColor: '#FFFFFF',
    barTextColor: '#333333',
    barSelectedColor: '#4CAF50',
    barBg: '#E8F5E9',
    inputBg: '#FFFFFF',
    inputBorder: '#A5D6A7',
    inputTextColor: '#333333',
    inputBorderRadius: 4,
    colorPrimary: '#4CAF50',
    colorSecondary: '#8BC34A',
    }),
    
    darkgreen: create({
    base: 'dark',
    appBg: '#1B5E20',
    appContentBg: '#2E7D32',
    appBorderColor: '#388E3C',
    appBorderRadius: 6,
    fontBase: '"Open Sans", sans-serif',
    fontCode: 'monospace',
    textColor: '#E0E0E0',
    textInverseColor: '#2E7D32',
    barTextColor: '#E0E0E0',
    barSelectedColor: '#66BB6A',
    barBg: '#1B5E20',
    inputBg: '#33691E',
    inputBorder: '#388E3C',
    inputTextColor: '#E0E0E0',
    inputBorderRadius: 4,
    colorPrimary: '#66BB6A',
    colorSecondary: '#81C784',
    }),
    
    lightpurple: create({
    base: 'light',
    appBg: '#F3E5F5',
    appContentBg: '#FFFFFF',
    appBorderColor: '#E1BEE7',
    appBorderRadius: 6,
    fontBase: '"Open Sans", sans-serif',
    fontCode: 'monospace',
    textColor: '#333333',
    textInverseColor: '#FFFFFF',
    barTextColor: '#333333',
    barSelectedColor: '#9C27B0',
    barBg: '#F8EAF6',
    inputBg: '#FFFFFF',
    inputBorder: '#CE93D8',
    inputTextColor: '#333333',
    inputBorderRadius: 4,
    colorPrimary: '#9C27B0',
    colorSecondary: '#BA68C8',
    }),
    
    darkpurple: create({
    base: 'dark',
    appBg: '#4A148C',
    appContentBg: '#6A1B9A',
    appBorderColor: '#7B1FA2',
    appBorderRadius: 6,
    fontBase: '"Open Sans", sans-serif',
    fontCode: 'monospace',
    textColor: '#E0E0E0',
    textInverseColor: '#6A1B9A',
    barTextColor: '#E0E0E0',
    barSelectedColor: '#AB47BC',
    barBg: '#4A148C',
    inputBg: '#311B92',
    inputBorder: '#7B1FA2',
    inputTextColor: '#E0E0E0',
    inputBorderRadius: 4,
    colorPrimary: '#AB47BC',
    colorSecondary: '#CE93D8',
    }),
};