export interface IconPropsBis {
    name: string;
    size?: number;
}

export interface IconProps {
  width?: number;
  height?: number;
  description?: string;
};

export type IconKeys = "add" |
"alt_route" |
"apps" |
"arrow_alt_down" |
"arrow_alt_down_left" |
"arrow_alt_down_right" |
"arrow_alt_left" |
"arrow_alt_right" |
"arrow_alt_up" |
"arrow_alt_up_left" |
"arrow_alt_up_right" |
"arrow_angle_down_left" |
"arrow_angle_down_right" |
"arrow_angle_up_left" |
"arrow_angle_up_right" |
"arrow_chevron_down" |
"arrow_chevron_left" |
"arrow_chevron_right" |
"arrow_chevron_up" |
"arrow_circle_chevron_down_filled" |
"arrow_circle_chevron_down_outlined" |
"arrow_circle_chevron_left_filled" |
"arrow_circle_chevron_left_outlined" |
"arrow_circle_chevron_right_filled" |
"arrow_circle_chevron_right_outlined" |
"arrow_circle_chevron_up_filled" |
"arrow_circle_chevron_up_outlined" |
"arrow_circle_down_filled" |
"arrow_circle_down_outlined" |
"arrow_circle_left_filled" |
"arrow_circle_left_outlined" |
"arrow_circle_right_filled" |
"arrow_circle_right_outlined" |
"arrow_circle_up_filled" |
"arrow_circle_up_outlined" |
"arrow_double_down" |
"arrow_double_left" |
"arrow_double_right" |
"arrow_double_up" |
"arrow_down" |
"arrow_down_left" |
"arrow_down_right" |
"arrow_left" |
"arrow_right" |
"arrow_up" |
"arrow_up_left" |
"arrow_up_right" |
"attach_file" |
"asterisk" |
"battery_alt_empty" |
"battery_alt_full" |
"battery_charging" |
"battery_empty" |
"battery_full" |
"bluetooth" |
"bluetooth_off" |
"chart_bar" |
"chart_bar_stacked" |
"check" |
"check_indeterminate" |
"check_small" |
"checkbox_empty" |
"close" |
"compare" |
"copy_all" |
"crisis_alert" |
"cut" |
"download" |
"download_done" |
"drag_handle" |
"drag_indicator" |
"exclamation" |
"explore_travel" |
"external_link" |
"filter" |
"filter_alt_filled" |
"filter_alt_off_filled" |
"filter_alt_off_outlined" |
"filter_alt_outlined" |
"filter_off" |
"first_page" |
"fit_screen_filled" |
"fit_screen_outlined" |
"forward" |
"fullscreen" |
"fullscreen_exit" |
"history" |
"home_filled" |
"home_outlined" |
"hourglass_empty" |
"info_i" |
"language" |
"last_page" |
"left_panel_close_filled" |
"left_panel_close_outlined" |
"left_panel_open_filled" |
"left_panel_open_outlined" |
"link" |
"link_off" |
"list" |
"location_disabled" |
"login" |
"logout" |
"menu" |
"menu_open" |
"monitoring" |
"more_down" |
"more_horiz" |
"more_up" |
"more_vert" |
"ohm" |
"open_in_full" |
"paste" |
"play_pause" |
"power_input" |
"power_plug" |
"power_settings" |
"priority_high" |
"public" |
"publish" |
"question_mark" |
"radar" |
"radio_button_empty" |
"redo" |
"reload" |
"remove" |
"reply" |
"reply_all" |
"right_panel_close_filled" |
"right_panel_close_outlined" |
"right_panel_open_filled" |
"right_panel_open_outlined" |
"route" |
"search" |
"settings_filled" |
"settings_outlined" |
"side_navigation" |
"sort" |
"support_agent" |
"timeline" |
"trending_down" |
"trending_flat" |
"trending_up" |
"tune" |
"undo" |
"upload" |
"water" |
"water_alt" |
"wifi" |
"wifi_off" |
"windmill" |
"zoom_in" |
"zoom_out" 


