export const DYNAMIC_TAB_MIN_WIDTH = 44;
export const DYNAMIC_TAB_WIDTH_RATIO = 0.15;
export const DYNAMIC_TAB_HIDDEN_TABS_WIDTH = 144;
export const DYNAMIC_TAB_CREATE_WIDTH = 44;
export const DYNAMIC_TAB_ACTION_BUTTONS_WIDTH = DYNAMIC_TAB_HIDDEN_TABS_WIDTH + DYNAMIC_TAB_CREATE_WIDTH;
export const DYNAMIC_TAB_CLOSE_ANIMATION_MS = 80;
export const DYNAMIC_TAB_ITEM_XSMALL_WIDTH = 48;
export const DYNAMIC_TAB_ITEM_SMALL_WIDTH = 104;
