import {
  Add,
  AltRoute,
  Apps,
  ArrowAltDown,
  ArrowAltDownLeft,
  ArrowAltDownRight,
  ArrowAltLeft,
  ArrowAltRight,
  ArrowAltUp,
  ArrowAltUpLeft,
  ArrowAltUpRight,
  ArrowAngleDownLeft,
  ArrowAngleDownRight,
  ArrowAngleUpLeft,
  ArrowAngleUpRight,
  ArrowChevronDown,
  ArrowChevronLeft,
  ArrowChevronRight,
  ArrowChevronUp,
  ArrowCircleChevronDownFilled,
  ArrowCircleChevronDownOutlined,
  ArrowCircleChevronLeftFilled,
  ArrowCircleChevronLeftOutlined,
  ArrowCircleChevronRightFilled,
  ArrowCircleChevronRightOutlined,
  ArrowCircleChevronUpFilled,
  ArrowCircleChevronUpOutlined,
  ArrowCircleDownFilled,
  ArrowCircleDownOutlined,
  ArrowCircleLeftFilled,
  ArrowCircleLeftOutlined,
  ArrowCircleRightFilled,
  ArrowCircleRightOutlined,
  ArrowCircleUpFilled,
  ArrowCircleUpOutlined,
  ArrowDoubleDown,
  ArrowDoubleLeft,
  ArrowDoubleRight,
  ArrowDoubleUp,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  AttachFile,
  Asterisk,
  BatteryAltEmpty,
  BatteryAltFull,
  BatteryCharging,
  BatteryEmpty,
  BatteryFull,
  Bluetooth,
  BluetoothOff,
  ChartBar,
  ChartBarStacked,
  Check,
  CheckIndeterminate,
  CheckSmall,
  CheckboxEmpty,
  Close,
  Compare,
  CopyAll,
  CrisisAlert,
  Cut,
  Download,
  DownloadDone,
  DragHandle,
  DragIndicator,
  Exclamation,
  ExploreTravel,
  ExternalLink,
  Filter,
  FilterAltFilled,
  FilterAltOffFilled,
  FilterAltOffOutlined,
  FilterAltOutlined,
  FilterOff,
  FirstPage,
  FitScreenFilled,
  FitScreenOutlined,
  Forward,
  Fullscreen,
  FullscreenExit,
  History,
  HomeFilled,
  HomeOutlined,
  HourglassEmpty,
  InfoI,
  Language,
  LastPage,
  LeftPanelCloseFilled,
  LeftPanelCloseOutlined,
  LeftPanelOpenFilled,
  LeftPanelOpenOutlined,
  Link,
  LinkOff,
  List,
  LocationDisabled,
  Login,
  Logout,
  Menu,
  MenuOpen,
  Monitoring,
  MoreDown,
  MoreHoriz,
  MoreUp,
  MoreVert,
  Ohm,
  OpenInFull,
  Paste,
  PlayPause,
  PowerInput,
  PowerPlug,
  PowerSettings,
  PriorityHigh,
  Public,
  Publish,
  QuestionMark,
  Radar,
  RadioButtonEmpty,
  Redo,
  Reload,
  Remove,
  Reply,
  ReplyAll,
  RightPanelCloseFilled,
  RightPanelCloseOutlined,
  RightPanelOpenFilled,
  RightPanelOpenOutlined,
  Route,
  Search,
  SettingsFilled,
  SettingsOutlined,
  SideNavigation,
  Sort,
  SupportAgent,
  Timeline,
  TrendingDown,
  TrendingFlat,
  TrendingUp,
  Tune,
  Undo,
  Upload,
  Water,
  WaterAlt,
  Wifi,
  WifiOff,
  Windmill,
  ZoomIn,
  ZoomOut,
} from '../icon/generated';

export const IconIds = {
  add: Add,
  alt_route: AltRoute,
  apps: Apps,
  arrow_alt_down: ArrowAltDown,
  arrow_alt_down_left: ArrowAltDownLeft,
  arrow_alt_down_right: ArrowAltDownRight,
  arrow_alt_left: ArrowAltLeft,
  arrow_alt_right: ArrowAltRight,
  arrow_alt_up: ArrowAltUp,
  arrow_alt_up_left: ArrowAltUpLeft,
  arrow_alt_up_right: ArrowAltUpRight,
  arrow_angle_down_left: ArrowAngleDownLeft,
  arrow_angle_down_right: ArrowAngleDownRight,
  arrow_angle_up_left: ArrowAngleUpLeft,
  arrow_angle_up_right: ArrowAngleUpRight,
  arrow_chevron_down: ArrowChevronDown,
  arrow_chevron_left: ArrowChevronLeft,
  arrow_chevron_right: ArrowChevronRight,
  arrow_chevron_up: ArrowChevronUp,
  arrow_circle_chevron_down_filled: ArrowCircleChevronDownFilled,
  arrow_circle_chevron_down_outlined: ArrowCircleChevronDownOutlined,
  arrow_circle_chevron_left_filled: ArrowCircleChevronLeftFilled,
  arrow_circle_chevron_left_outlined: ArrowCircleChevronLeftOutlined,
  arrow_circle_chevron_right_filled: ArrowCircleChevronRightFilled,
  arrow_circle_chevron_right_outlined: ArrowCircleChevronRightOutlined,
  arrow_circle_chevron_up_filled: ArrowCircleChevronUpFilled,
  arrow_circle_chevron_up_outlined: ArrowCircleChevronUpOutlined,
  arrow_circle_down_filled: ArrowCircleDownFilled,
  arrow_circle_down_outlined: ArrowCircleDownOutlined,
  arrow_circle_left_filled: ArrowCircleLeftFilled,
  arrow_circle_left_outlined: ArrowCircleLeftOutlined,
  arrow_circle_right_filled: ArrowCircleRightFilled,
  arrow_circle_right_outlined: ArrowCircleRightOutlined,
  arrow_circle_up_filled: ArrowCircleUpFilled,
  arrow_circle_up_outlined: ArrowCircleUpOutlined,
  arrow_double_down: ArrowDoubleDown,
  arrow_double_left: ArrowDoubleLeft,
  arrow_double_right: ArrowDoubleRight,
  arrow_double_up: ArrowDoubleUp,
  arrow_down: ArrowDown,
  arrow_down_left: ArrowDownLeft,
  arrow_down_right: ArrowDownRight,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  arrow_up: ArrowUp,
  arrow_up_left: ArrowUpLeft,
  arrow_up_right: ArrowUpRight,
  attach_file: AttachFile,
  asterisk: Asterisk,
  battery_alt_empty: BatteryAltEmpty,
  battery_alt_full: BatteryAltFull,
  battery_charging: BatteryCharging,
  battery_empty: BatteryEmpty,
  battery_full: BatteryFull,
  bluetooth: Bluetooth,
  bluetooth_off: BluetoothOff,
  chart_bar: ChartBar,
  chart_bar_stacked: ChartBarStacked,
  check: Check,
  check_indeterminate: CheckIndeterminate,
  check_small: CheckSmall,
  checkbox_empty: CheckboxEmpty,
  close: Close,
  compare: Compare,
  copy_all: CopyAll,
  crisis_alert: CrisisAlert,
  cut: Cut,
  download: Download,
  download_done: DownloadDone,
  drag_handle: DragHandle,
  drag_indicator: DragIndicator,
  exclamation: Exclamation,
  explore_travel: ExploreTravel,
  external_link: ExternalLink,
  filter: Filter,
  filter_alt_filled: FilterAltFilled,
  filter_alt_off_filled: FilterAltOffFilled,
  filter_alt_off_outlined: FilterAltOffOutlined,
  filter_alt_outlined: FilterAltOutlined,
  filter_off: FilterOff,
  first_page: FirstPage,
  fit_screen_filled: FitScreenFilled,
  fit_screen_outlined: FitScreenOutlined,
  forward: Forward,
  fullscreen: Fullscreen,
  fullscreen_exit: FullscreenExit,
  history: History,
  home_filled: HomeFilled,
  home_outlined: HomeOutlined,
  hourglass_empty: HourglassEmpty,
  info_i: InfoI,
  language: Language,
  last_page: LastPage,
  left_panel_close_filled: LeftPanelCloseFilled,
  left_panel_close_outlined: LeftPanelCloseOutlined,
  left_panel_open_filled: LeftPanelOpenFilled,
  left_panel_open_outlined: LeftPanelOpenOutlined,
  link: Link,
  link_off: LinkOff,
  list: List,
  location_disabled: LocationDisabled,
  login: Login,
  logout: Logout,
  menu: Menu,
  menu_open: MenuOpen,
  monitoring: Monitoring,
  more_down: MoreDown,
  more_horiz: MoreHoriz,
  more_up: MoreUp,
  more_vert: MoreVert,
  ohm: Ohm,
  open_in_full: OpenInFull,
  paste: Paste,
  play_pause: PlayPause,
  power_input: PowerInput,
  power_plug: PowerPlug,
  power_settings: PowerSettings,
  priority_high: PriorityHigh,
  public: Public,
  publish: Publish,
  question_mark: QuestionMark,
  radar: Radar,
  radio_button_empty: RadioButtonEmpty,
  redo: Redo,
  reload: Reload,
  remove: Remove,
  reply: Reply,
  reply_all: ReplyAll,
  right_panel_close_filled: RightPanelCloseFilled,
  right_panel_close_outlined: RightPanelCloseOutlined,
  right_panel_open_filled: RightPanelOpenFilled,
  right_panel_open_outlined: RightPanelOpenOutlined,
  route: Route,
  search: Search,
  settings_filled: SettingsFilled,
  settings_outlined: SettingsOutlined,
  side_navigation: SideNavigation,
  sort: Sort,
  support_agent: SupportAgent,
  timeline: Timeline,
  trending_down: TrendingDown,
  trending_flat: TrendingFlat,
  trending_up: TrendingUp,
  tune: Tune,
  undo: Undo,
  upload: Upload,
  water: Water,
  water_alt: WaterAlt,
  wifi: Wifi,
  wifi_off: WifiOff,
  windmill: Windmill,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
};
