import {
  Add,
  AltRoute,
  Apps,
  ArrowAltDown,
  ArrowAltDownLeft,
  ArrowAltDownRight,
  ArrowAltLeft,
  ArrowAltRight,
  ArrowAltUp,
  ArrowAltUpLeft,
  ArrowAltUpRight,
  ArrowAngleDownLeft,
  ArrowAngleDownRight,
  ArrowAngleUpLeft,
  ArrowAngleUpRight,
  ArrowChevronDown,
  ArrowChevronLeft,
  ArrowChevronRight,
  ArrowChevronUp,
  ArrowCircleChevronDownFilled,
  ArrowCircleChevronDownOutlined,
  ArrowCircleChevronLeftFilled,
  ArrowCircleChevronLeftOutlined,
  ArrowCircleChevronRightFilled,
  ArrowCircleChevronRightOutlined,
  ArrowCircleChevronUpFilled,
  ArrowCircleChevronUpOutlined,
  ArrowCircleDownFilled,
  ArrowCircleDownOutlined,
  ArrowCircleLeftFilled,
  ArrowCircleLeftOutlined,
  ArrowCircleRightFilled,
  ArrowCircleRightOutlined,
  ArrowCircleUpFilled,
  ArrowCircleUpOutlined,
  ArrowDoubleDown,
  ArrowDoubleLeft,
  ArrowDoubleRight,
  ArrowDoubleUp,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  AttachFile,
  Asterisk,
  BatteryAltEmpty,
  BatteryAltFull,
  BatteryCharging,
  BatteryEmpty,
  BatteryFull,
  Bluetooth,
  BluetoothOff,
  ChartBar,
  ChartBarStacked,
  Check,
  CheckIndeterminate,
  CheckSmall,
  CheckboxEmpty,
  Close,
  Compare,
  CopyAll,
  CrisisAlert,
  Cut,
  Download,
  DownloadDone,
  DragHandle,
  DragIndicator,
  Exclamation,
  ExploreTravel,
  ExternalLink,
  Filter,
  FilterAltFilled,
  FilterAltOffFilled,
  FilterAltOffOutlined,
  FilterAltOutlined,
  FilterOff,
  FirstPage,
  FitScreenFilled,
  FitScreenOutlined,
  Forward,
  Fullscreen,
  FullscreenExit,
  History,
  HomeFilled,
  HomeOutlined,
  HourglassEmpty,
  InfoI,
  Language,
  LastPage,
  LeftPanelCloseFilled,
  LeftPanelCloseOutlined,
  LeftPanelOpenFilled,
  LeftPanelOpenOutlined,
  Link,
  LinkOff,
  List,
  LocationDisabled,
  Login,
  Logout,
  Menu,
  MenuOpen,
  Monitoring,
  MoreDown,
  MoreHoriz,
  MoreUp,
  MoreVert,
  Ohm,
  OpenInFull,
  Paste,
  PlayPause,
  PowerInput,
  PowerPlug,
  PowerSettings,
  PriorityHigh,
  Public,
  Publish,
  QuestionMark,
  Radar,
  RadioButtonEmpty,
  Redo,
  Reload,
  Remove,
  Reply,
  ReplyAll,
  RightPanelCloseFilled,
  RightPanelCloseOutlined,
  RightPanelOpenFilled,
  RightPanelOpenOutlined,
  Route,
  Search,
  SettingsFilled,
  SettingsOutlined,
  SideNavigation,
  Sort,
  SupportAgent,
  Timeline,
  TrendingDown,
  TrendingFlat,
  TrendingUp,
  Tune,
  Undo,
  Upload,
  Water,
  WaterAlt,
  Wifi,
  WifiOff,
  Windmill,
  ZoomIn,
  ZoomOut,
  AddCircleFilled,
  AddCircleOutlined,
  AdminPanelSettingsFilled,
  AdminPanelSettingsOutlined,
  AnalyticsFilled,
  AnalyticsOutlined,
  ArchiveFilled,
  ArchiveOutlined,
  ArrowDropDown,
  ArrowDropUp,
  ArticleFilled,
  ArticleOutlined,
  AssignmentCompleteFilled,
  AssignmentCompleteOutlined,
  AssignmentFilled,
  AssignmentOutlined,
  BatteryAlertFilled,
  BatteryAlertOutlined,
  BatteryChargingFullFilled,
  BatteryChargingFullOutlined,
  BoltAltCircleFilled,
  BoltAltCircleOutlined,
  BoltCircleFilled,
  BoltCircleOutlined,
  BoltFilled,
  BoltOutlined,
  BookmarkFilled,
  BookmarkOutlined,
  BookmarksFilled,
  BookmarksOutlined,
  BuildFilled,
  BuildOutlined,
  CalendarAvailableFilled,
  CalendarAvailableOutlined,
  CalendarBusyFilled,
  CalendarBusyOutlined,
  CalendarMonthFilled,
  CalendarMonthOutlined,
  CalendarTodayFilled,
  CalendarTodayOutlined,
  CallFilled,
  CallOutlined,
  CategoryFilled,
  CategoryOutlined,
  ChartAddFilled,
  ChartAddOutlined,
  ChartAreaFilled,
  ChartAreaOutlined,
  ChartPieFilled,
  ChartPieOutlined,
  ChartTableFilled,
  ChartTableOutlined,
  ChatAltFilled,
  ChatAltOutlined,
  ChatAltUnreadFilled,
  ChatAltUnreadOutlined,
  ChatFilled,
  ChatOutlined,
  ChatUnreadFilled,
  ChatUnreadOutlined,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckboxFilled,
  CheckboxIndeterminateFilled,
  CheckboxOutlined,
  ClockFilled,
  ClockOutlined,
  CloudDownloadFilled,
  CloudDownloadOutlined,
  CloudFilled,
  CloudOffFilled,
  CloudOffOutlined,
  CloudOutlined,
  CloudUploadFilled,
  CloudUploadOutlined,
  CommentAddFilled,
  CommentAddOutlined,
  CommentFilled,
  CommentOutlined,
  CopyFilled,
  CopyOutlined,
  DangerousFilled,
  DangerousOutlined,
  DashboardFilled,
  DashboardOutlined,
  DatabaseFilled,
  DatabaseOutlined,
  DeleteFilled,
  DeleteOutlined,
  DesktopFilled,
  DesktopOutlined,
  DevicesFilled,
  DevicesOutlined,
  DraftFilled,
  DraftOutlined,
  EcoFilled,
  EcoOutlined,
  EditFilled,
  EditOutlined,
  ElectricMeterFilled,
  ElectricMeterOutlined,
  ErrorFilled,
  ErrorOutlined,
  ExploreFilled,
  ExploreOffFilled,
  ExploreOffOutlined,
  ExploreOutlined,
  FastForwardFilled,
  FastForwardOutlined,
  FastRewindFilled,
  FastRewindOutlined,
  FeedbackFilled,
  FeedbackOutlined,
  FileCopyFilled,
  FileCopyOutlined,
  FileDownloadFilled,
  FileDownloadOutlined,
  FileUploadFilled,
  FileUploadOutlined,
  FireFilled,
  FireOutlined,
  FlagFilled,
  FlagOutlined,
  FlashFilled,
  FlashOffFilled,
  FlashOffOutlined,
  FlashOutlined,
  FolderAddFilled,
  FolderAddOutlined,
  FolderFilled,
  FolderMoveFilled,
  FolderMoveOutlined,
  FolderOpenFilled,
  FolderOpenOutlined,
  FolderOutlined,
  FolderSharedFilled,
  FolderSharedOutlined,
  ForumFilled,
  ForumOutlined,
  GroupAddFilled,
  GroupAddOutlined,
  GroupFilled,
  GroupOutlined,
  GroupsFilled,
  GroupsOutlined,
  HeadphonesFilled,
  HeadphonesOutlined,
  HeartFilled,
  HeartOutlined,
  HelpFilled,
  HelpOutlined,
  HourglassFilled,
  HourglassOutlined,
  IconAppearanceOutlined,
  ImageBrokenFilled,
  ImageBrokenOutlined,
  ImageFilled,
  ImageGalleryFilled,
  ImageGalleryOutlined,
  ImageOutlined,
  InboxFilled,
  InboxOutlined,
  InfoFilled,
  InfoOutlined,
  KeepFilled,
  KeepOffFilled,
  KeepOffOutlined,
  KeepOutlined,
  LabelFilled,
  LabelOutlined,
  LaptopFilled,
  LaptopOutlined,
  LightOffFilled,
  LightOffOutlined,
  LightbulbAltFilled,
  LightbulbAltOutlined,
  LightbulbCircleFilled,
  LightbulbCircleOutlined,
  LightbulbFilled,
  LightbulbOutlined,
  ListAltFilled,
  ListAltOutlined,
  LocationMeFilled,
  LocationMeOutlined,
  LocationOffFilled,
  LocationOffOutlined,
  LocationOnFilled,
  LocationOnOutlined,
  LockFilled,
  LockOpenFilled,
  LockOpenOutlined,
  LockOpenRightFilled,
  LockOpenRightOutlined,
  LockOutlined,
  MailFilled,
  MailOutlined,
  MailUnreadFilled,
  MailUnreadOutlined,
  MapFilled,
  MapOutlined,
  MicFilled,
  MicOffFilled,
  MicOffOutlined,
  MicOutlined,
  ModeDarkFilled,
  ModeDarkOutlined,
  ModeLightFilled,
  ModeLightOutlined,
  NotificationFilled,
  NotificationImportantFilled,
  NotificationImportantOutlined,
  NotificationOffFilled,
  NotificationOffOutlined,
  NotificationOutlined,
  NotificationUnreadFilled,
  NotificationUnreadOutlined,
  PaletteFilled,
  PaletteOutlined,
  PauseCircleFilled,
  PauseCircleOutlined,
  PauseFilled,
  PauseOutlined,
  PhotoCameraFilled,
  PhotoCameraOutlined,
  PlayCircleFilled,
  PlayCircleOutlined,
  PlayFilled,
  PlayOutlined,
  PowerFilled,
  PowerOffFilled,
  PowerOffOutlined,
  PowerOutlined,
  PowerPlugConnectFilled,
  PowerPlugConnectOutlined,
  PowerSettingsCircleFilled,
  PowerSettingsCircleOutlined,
  PowerSolarFilled,
  PowerSolarOutlined,
  PowerSwitchFilled,
  PowerSwitchOutlined,
  PowerWindFilled,
  PowerWindOutlined,
  PrintFilled,
  PrintOutlined,
  SaveFilled,
  SaveOutlined,
  SendFilled,
  SendOutlined,
  ShareFilled,
  ShareOutlined,
  SkipNextFilled,
  SkipNextOutlined,
  SkipPreviousFilled,
  SkipPreviousOutlined,
  SmartphoneFilled,
  SmartphoneOutlined,
  StarFilled,
  StarOutlined,
  StickyNoteFilled,
  StickyNoteOutlined,
  StopCircleFilled,
  StopCircleOutlined,
  StopFilled,
  StopOutlined,
  SubtitlesFilled,
  SubtitlesOutlined,
  TextSnippetFilled,
  TextSnippetOutlined,
  TrashRestoreFilled,
  TrashRestoreOutlined,
  UnarchiveFilled,
  UnarchiveOutlined,
  UserAddFilled,
  UserAddOutlined,
  UserCircleFilled,
  UserCircleOutlined,
  UserFilled,
  UserOutlined,
  UserSettingsFilled,
  UserSettingsOutlined,
  VerifiedFilled,
  VerifiedOutlined,
  VideoCameraFilled,
  VideoCameraOffFilled,
  VideoCameraOffOutlined,
  VideoCameraOutlined,
  VideoGalleryFilled,
  VideoGalleryOutlined,
  ViewAgendaFilled,
  ViewAgendaOutlined,
  ViewColumnFilled,
  ViewColumnOutlined,
  ViewGridFilled,
  ViewGridOutlined,
  ViewKanbanFilled,
  ViewKanbanOutlined,
  ViewModuleFilled,
  ViewModuleOutlined,
  ViewTimelineFilled,
  ViewTimelineOutlined,
  VisibilityHideFilled,
  VisibilityHideOutlined,
  VisibilityShowFilled,
  VisibilityShowOutlined,
  VolumeDownFilled,
  VolumeDownOutlined,
  VolumeMuteFilled,
  VolumeMuteOutlined,
  VolumeOffFilled,
  VolumeOffOutlined,
  VolumeUpFilled,
  VolumeUpOutlined,
  WarningFilled,
  WarningOutlined,
  WaterdropFilled,
  WaterdropOutlined,
} from '../icon/generated';

// Mapping des noms de fichiers SVG vers PascalCase
export const IconIds = {
  add_circle_filled: AddCircleFilled,
  add_circle_outlined: AddCircleOutlined,
  add: Add,
  admin_panel_settings_filled: AdminPanelSettingsFilled,
  admin_panel_settings_outlined: AdminPanelSettingsOutlined,
  alt_route: AltRoute,
  analytics_filled: AnalyticsFilled,
  analytics_outlined: AnalyticsOutlined,
  apps: Apps,
  archive_filled: ArchiveFilled,
  archive_outlined: ArchiveOutlined,
  arrow_alt_down_left: ArrowAltDownLeft,
  arrow_alt_down_right: ArrowAltDownRight,
  arrow_alt_down: ArrowAltDown,
  arrow_alt_left: ArrowAltLeft,
  arrow_alt_right: ArrowAltRight,
  arrow_alt_up_left: ArrowAltUpLeft,
  arrow_alt_up_right: ArrowAltUpRight,
  arrow_alt_up: ArrowAltUp,
  arrow_angle_down_left: ArrowAngleDownLeft,
  arrow_angle_down_right: ArrowAngleDownRight,
  arrow_angle_up_left: ArrowAngleUpLeft,
  arrow_angle_up_right: ArrowAngleUpRight,
  arrow_chevron_down: ArrowChevronDown,
  arrow_chevron_left: ArrowChevronLeft,
  arrow_chevron_right: ArrowChevronRight,
  arrow_chevron_up: ArrowChevronUp,
  arrow_circle_chevron_down_filled: ArrowCircleChevronDownFilled,
  arrow_circle_chevron_down_outlined: ArrowCircleChevronDownOutlined,
  arrow_circle_chevron_left_filled: ArrowCircleChevronLeftFilled,
  arrow_circle_chevron_left_outlined: ArrowCircleChevronLeftOutlined,
  arrow_circle_chevron_right_filled: ArrowCircleChevronRightFilled,
  arrow_circle_chevron_right_outlined: ArrowCircleChevronRightOutlined,
  arrow_circle_chevron_up_filled: ArrowCircleChevronUpFilled,
  arrow_circle_chevron_up_outlined: ArrowCircleChevronUpOutlined,
  arrow_circle_down_filled: ArrowCircleDownFilled,
  arrow_circle_down_outlined: ArrowCircleDownOutlined,
  arrow_circle_left_filled: ArrowCircleLeftFilled,
  arrow_circle_left_outlined: ArrowCircleLeftOutlined,
  arrow_circle_right_filled: ArrowCircleRightFilled,
  arrow_circle_right_outlined: ArrowCircleRightOutlined,
  arrow_circle_up_filled: ArrowCircleUpFilled,
  arrow_circle_up_outlined: ArrowCircleUpOutlined,
  arrow_double_down: ArrowDoubleDown,
  arrow_double_left: ArrowDoubleLeft,
  arrow_double_right: ArrowDoubleRight,
  arrow_double_up: ArrowDoubleUp,
  arrow_down_left: ArrowDownLeft,
  arrow_down_right: ArrowDownRight,
  arrow_down: ArrowDown,
  arrow_drop_down: ArrowDropDown,
  arrow_drop_up: ArrowDropUp,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  arrow_up_left: ArrowUpLeft,
  arrow_up_right: ArrowUpRight,
  arrow_up: ArrowUp,
  article_filled: ArticleFilled,
  article_outlined: ArticleOutlined,
  assignment_complete_filled: AssignmentCompleteFilled,
  assignment_complete_outlined: AssignmentCompleteOutlined,
  assignment_filled: AssignmentFilled,
  assignment_outlined: AssignmentOutlined,
  asterisk: Asterisk,
  attach_file: AttachFile,
  battery_alert_filled: BatteryAlertFilled,
  battery_alert_outlined: BatteryAlertOutlined,
  battery_alt_empty: BatteryAltEmpty,
  battery_alt_full: BatteryAltFull,
  battery_charging_full_filled: BatteryChargingFullFilled,
  battery_charging_full_outlined: BatteryChargingFullOutlined,
  battery_charging: BatteryCharging,
  battery_empty: BatteryEmpty,
  battery_full: BatteryFull,
  bluetooth_off: BluetoothOff,
  bluetooth: Bluetooth,
  bolt_alt_circle_filled: BoltAltCircleFilled,
  bolt_alt_circle_outlined: BoltAltCircleOutlined,
  bolt_circle_filled: BoltCircleFilled,
  bolt_circle_outlined: BoltCircleOutlined,
  bolt_filled: BoltFilled,
  bolt_outlined: BoltOutlined,
  bookmark_filled: BookmarkFilled,
  bookmark_outlined: BookmarkOutlined,
  bookmarks_filled: BookmarksFilled,
  bookmarks_outlined: BookmarksOutlined,
  build_filled: BuildFilled,
  build_outlined: BuildOutlined,
  calendar_available_filled: CalendarAvailableFilled,
  calendar_available_outlined: CalendarAvailableOutlined,
  calendar_busy_filled: CalendarBusyFilled,
  calendar_busy_outlined: CalendarBusyOutlined,
  calendar_month_filled: CalendarMonthFilled,
  calendar_month_outlined: CalendarMonthOutlined,
  calendar_today_filled: CalendarTodayFilled,
  calendar_today_outlined: CalendarTodayOutlined,
  call_filled: CallFilled,
  call_outlined: CallOutlined,
  category_filled: CategoryFilled,
  category_outlined: CategoryOutlined,
  chart_add_filled: ChartAddFilled,
  chart_add_outlined: ChartAddOutlined,
  chart_area_filled: ChartAreaFilled,
  chart_area_outlined: ChartAreaOutlined,
  chart_bar_stacked: ChartBarStacked,
  chart_bar: ChartBar,
  chart_pie_filled: ChartPieFilled,
  chart_pie_outlined: ChartPieOutlined,
  chart_table_filled: ChartTableFilled,
  chart_table_outlined: ChartTableOutlined,
  chat_alt_filled: ChatAltFilled,
  chat_alt_outlined: ChatAltOutlined,
  chat_alt_unread_filled: ChatAltUnreadFilled,
  chat_alt_unread_outlined: ChatAltUnreadOutlined,
  chat_filled: ChatFilled,
  chat_outlined: ChatOutlined,
  chat_unread_filled: ChatUnreadFilled,
  chat_unread_outlined: ChatUnreadOutlined,
  check_circle_filled: CheckCircleFilled,
  check_circle_outlined: CheckCircleOutlined,
  check_indeterminate: CheckIndeterminate,
  check_small: CheckSmall,
  check: Check,
  checkbox_empty: CheckboxEmpty,
  checkbox_filled: CheckboxFilled,
  checkbox_indeterminate_filled: CheckboxIndeterminateFilled,
  checkbox_outlined: CheckboxOutlined,
  clock_filled: ClockFilled,
  clock_outlined: ClockOutlined,
  close: Close,
  cloud_download_filled: CloudDownloadFilled,
  cloud_download_outlined: CloudDownloadOutlined,
  cloud_filled: CloudFilled,
  cloud_off_filled: CloudOffFilled,
  cloud_off_outlined: CloudOffOutlined,
  cloud_outlined: CloudOutlined,
  cloud_upload_filled: CloudUploadFilled,
  cloud_upload_outlined: CloudUploadOutlined,
  comment_add_filled: CommentAddFilled,
  comment_add_outlined: CommentAddOutlined,
  comment_filled: CommentFilled,
  comment_outlined: CommentOutlined,
  compare: Compare,
  copy_all: CopyAll,
  copy_filled: CopyFilled,
  copy_outlined: CopyOutlined,
  crisis_alert: CrisisAlert,
  cut: Cut,
  dangerous_filled: DangerousFilled,
  dangerous_outlined: DangerousOutlined,
  dashboard_filled: DashboardFilled,
  dashboard_outlined: DashboardOutlined,
  database_filled: DatabaseFilled,
  database_outlined: DatabaseOutlined,
  delete_filled: DeleteFilled,
  delete_outlined: DeleteOutlined,
  desktop_filled: DesktopFilled,
  desktop_outlined: DesktopOutlined,
  devices_filled: DevicesFilled,
  devices_outlined: DevicesOutlined,
  download_done: DownloadDone,
  download: Download,
  draft_filled: DraftFilled,
  draft_outlined: DraftOutlined,
  drag_handle: DragHandle,
  drag_indicator: DragIndicator,
  eco_filled: EcoFilled,
  eco_outlined: EcoOutlined,
  edit_filled: EditFilled,
  edit_outlined: EditOutlined,
  electric_meter_filled: ElectricMeterFilled,
  electric_meter_outlined: ElectricMeterOutlined,
  error_filled: ErrorFilled,
  error_outlined: ErrorOutlined,
  exclamation: Exclamation,
  explore_filled: ExploreFilled,
  explore_off_filled: ExploreOffFilled,
  explore_off_outlined: ExploreOffOutlined,
  explore_outlined: ExploreOutlined,
  explore_travel: ExploreTravel,
  external_link: ExternalLink,
  fast_forward_filled: FastForwardFilled,
  fast_forward_outlined: FastForwardOutlined,
  fast_rewind_filled: FastRewindFilled,
  fast_rewind_outlined: FastRewindOutlined,
  feedback_filled: FeedbackFilled,
  feedback_outlined: FeedbackOutlined,
  file_copy_filled: FileCopyFilled,
  file_copy_outlined: FileCopyOutlined,
  file_download_filled: FileDownloadFilled,
  file_download_outlined: FileDownloadOutlined,
  file_upload_filled: FileUploadFilled,
  file_upload_outlined: FileUploadOutlined,
  filter_alt_filled: FilterAltFilled,
  filter_alt_off_filled: FilterAltOffFilled,
  filter_alt_off_outlined: FilterAltOffOutlined,
  filter_alt_outlined: FilterAltOutlined,
  filter_off: FilterOff,
  filter: Filter,
  fire_filled: FireFilled,
  fire_outlined: FireOutlined,
  first_page: FirstPage,
  fit_screen_filled: FitScreenFilled,
  fit_screen_outlined: FitScreenOutlined,
  flag_filled: FlagFilled,
  flag_outlined: FlagOutlined,
  flash_filled: FlashFilled,
  flash_off_filled: FlashOffFilled,
  flash_off_outlined: FlashOffOutlined,
  flash_outlined: FlashOutlined,
  folder_add_filled: FolderAddFilled,
  folder_add_outlined: FolderAddOutlined,
  folder_filled: FolderFilled,
  folder_move_filled: FolderMoveFilled,
  folder_move_outlined: FolderMoveOutlined,
  folder_open_filled: FolderOpenFilled,
  folder_open_outlined: FolderOpenOutlined,
  folder_outlined: FolderOutlined,
  folder_shared_filled: FolderSharedFilled,
  folder_shared_outlined: FolderSharedOutlined,
  forum_filled: ForumFilled,
  forum_outlined: ForumOutlined,
  forward: Forward,
  fullscreen_exit: FullscreenExit,
  fullscreen: Fullscreen,
  group_add_filled: GroupAddFilled,
  group_add_outlined: GroupAddOutlined,
  group_filled: GroupFilled,
  group_outlined: GroupOutlined,
  groups_filled: GroupsFilled,
  groups_outlined: GroupsOutlined,
  headphones_filled: HeadphonesFilled,
  headphones_outlined: HeadphonesOutlined,
  heart_filled: HeartFilled,
  heart_outlined: HeartOutlined,
  help_filled: HelpFilled,
  help_outlined: HelpOutlined,
  history: History,
  home_filled: HomeFilled,
  home_outlined: HomeOutlined,
  hourglass_empty: HourglassEmpty,
  hourglass_filled: HourglassFilled,
  hourglass_outlined: HourglassOutlined,
  iconAppearance_outlined: IconAppearanceOutlined,
  image_broken_filled: ImageBrokenFilled,
  image_broken_outlined: ImageBrokenOutlined,
  image_filled: ImageFilled,
  image_gallery_filled: ImageGalleryFilled,
  image_gallery_outlined: ImageGalleryOutlined,
  image_outlined: ImageOutlined,
  inbox_filled: InboxFilled,
  inbox_outlined: InboxOutlined,
  info_filled: InfoFilled,
  info_i: InfoI,
  info_outlined: InfoOutlined,
  keep_filled: KeepFilled,
  keep_off_filled: KeepOffFilled,
  keep_off_outlined: KeepOffOutlined,
  keep_outlined: KeepOutlined,
  label_filled: LabelFilled,
  label_outlined: LabelOutlined,
  language: Language,
  laptop_filled: LaptopFilled,
  laptop_outlined: LaptopOutlined,
  last_page: LastPage,
  left_panel_close_filled: LeftPanelCloseFilled,
  left_panel_close_outlined: LeftPanelCloseOutlined,
  left_panel_open_filled: LeftPanelOpenFilled,
  left_panel_open_outlined: LeftPanelOpenOutlined,
  light_off_filled: LightOffFilled,
  light_off_outlined: LightOffOutlined,
  lightbulb_alt_filled: LightbulbAltFilled,
  lightbulb_alt_outlined: LightbulbAltOutlined,
  lightbulb_circle_filled: LightbulbCircleFilled,
  lightbulb_circle_outlined: LightbulbCircleOutlined,
  lightbulb_filled: LightbulbFilled,
  lightbulb_outlined: LightbulbOutlined,
  link_off: LinkOff,
  link: Link,
  list_alt_filled: ListAltFilled,
  list_alt_outlined: ListAltOutlined,
  list: List,
  location_disabled: LocationDisabled,
  location_me_filled: LocationMeFilled,
  location_me_outlined: LocationMeOutlined,
  location_off_filled: LocationOffFilled,
  location_off_outlined: LocationOffOutlined,
  location_on_filled: LocationOnFilled,
  location_on_outlined: LocationOnOutlined,
  lock_filled: LockFilled,
  lock_open_filled: LockOpenFilled,
  lock_open_outlined: LockOpenOutlined,
  lock_open_right_filled: LockOpenRightFilled,
  lock_open_right_outlined: LockOpenRightOutlined,
  lock_outlined: LockOutlined,
  login: Login,
  logout: Logout,
  mail_filled: MailFilled,
  mail_outlined: MailOutlined,
  mail_unread_filled: MailUnreadFilled,
  mail_unread_outlined: MailUnreadOutlined,
  map_filled: MapFilled,
  map_outlined: MapOutlined,
  menu_open: MenuOpen,
  menu: Menu,
  mic_filled: MicFilled,
  mic_off_filled: MicOffFilled,
  mic_off_outlined: MicOffOutlined,
  mic_outlined: MicOutlined,
  mode_dark_filled: ModeDarkFilled,
  mode_dark_outlined: ModeDarkOutlined,
  mode_light_filled: ModeLightFilled,
  mode_light_outlined: ModeLightOutlined,
  monitoring: Monitoring,
  more_down: MoreDown,
  more_horiz: MoreHoriz,
  more_up: MoreUp,
  more_vert: MoreVert,
  notification_filled: NotificationFilled,
  notification_important_filled: NotificationImportantFilled,
  notification_important_outlined: NotificationImportantOutlined,
  notification_off_filled: NotificationOffFilled,
  notification_off_outlined: NotificationOffOutlined,
  notification_outlined: NotificationOutlined,
  notification_unread_filled: NotificationUnreadFilled,
  notification_unread_outlined: NotificationUnreadOutlined,
  ohm: Ohm,
  open_in_full: OpenInFull,
  palette_filled: PaletteFilled,
  palette_outlined: PaletteOutlined,
  paste: Paste,
  pause_circle_filled: PauseCircleFilled,
  pause_circle_outlined: PauseCircleOutlined,
  pause_filled: PauseFilled,
  pause_outlined: PauseOutlined,
  photo_camera_filled: PhotoCameraFilled,
  photo_camera_outlined: PhotoCameraOutlined,
  play_circle_filled: PlayCircleFilled,
  play_circle_outlined: PlayCircleOutlined,
  play_filled: PlayFilled,
  play_outlined: PlayOutlined,
  play_pause: PlayPause,
  power_filled: PowerFilled,
  power_input: PowerInput,
  power_off_filled: PowerOffFilled,
  power_off_outlined: PowerOffOutlined,
  power_outlined: PowerOutlined,
  power_plug_connect_filled: PowerPlugConnectFilled,
  power_plug_connect_outlined: PowerPlugConnectOutlined,
  power_plug: PowerPlug,
  power_settings_circle_filled: PowerSettingsCircleFilled,
  power_settings_circle_outlined: PowerSettingsCircleOutlined,
  power_settings: PowerSettings,
  power_solar_filled: PowerSolarFilled,
  power_solar_outlined: PowerSolarOutlined,
  power_switch_filled: PowerSwitchFilled,
  power_switch_outlined: PowerSwitchOutlined,
  power_wind_filled: PowerWindFilled,
  power_wind_outlined: PowerWindOutlined,
  print_filled: PrintFilled,
  print_outlined: PrintOutlined,
  priority_high: PriorityHigh,
  public: Public,
  publish: Publish,
  question_mark: QuestionMark,
  radar: Radar,
  radio_button_empty: RadioButtonEmpty,
  redo: Redo,
  reload: Reload,
  remove: Remove,
  reply_all: ReplyAll,
  reply: Reply,
  right_panel_close_filled: RightPanelCloseFilled,
  right_panel_close_outlined: RightPanelCloseOutlined,
  right_panel_open_filled: RightPanelOpenFilled,
  right_panel_open_outlined: RightPanelOpenOutlined,
  route: Route,
  save_filled: SaveFilled,
  save_outlined: SaveOutlined,
  search: Search,
  send_filled: SendFilled,
  send_outlined: SendOutlined,
  settings_filled: SettingsFilled,
  settings_outlined: SettingsOutlined,
  share_filled: ShareFilled,
  share_outlined: ShareOutlined,
  side_navigation: SideNavigation,
  skip_next_filled: SkipNextFilled,
  skip_next_outlined: SkipNextOutlined,
  skip_previous_filled: SkipPreviousFilled,
  skip_previous_outlined: SkipPreviousOutlined,
  smartphone_filled: SmartphoneFilled,
  smartphone_outlined: SmartphoneOutlined,
  sort: Sort,
  star_filled: StarFilled,
  star_outlined: StarOutlined,
  sticky_note_filled: StickyNoteFilled,
  sticky_note_outlined: StickyNoteOutlined,
  stop_circle_filled: StopCircleFilled,
  stop_circle_outlined: StopCircleOutlined,
  stop_filled: StopFilled,
  stop_outlined: StopOutlined,
  subtitles_filled: SubtitlesFilled,
  subtitles_outlined: SubtitlesOutlined,
  support_agent: SupportAgent,
  text_snippet_filled: TextSnippetFilled,
  text_snippet_outlined: TextSnippetOutlined,
  timeline: Timeline,
  trash_restore_filled: TrashRestoreFilled,
  trash_restore_outlined: TrashRestoreOutlined,
  trending_down: TrendingDown,
  trending_flat: TrendingFlat,
  trending_up: TrendingUp,
  tune: Tune,
  unarchive_filled: UnarchiveFilled,
  unarchive_outlined: UnarchiveOutlined,
  undo: Undo,
  upload: Upload,
  user_add_filled: UserAddFilled,
  user_add_outlined: UserAddOutlined,
  user_circle_filled: UserCircleFilled,
  user_circle_outlined: UserCircleOutlined,
  user_filled: UserFilled,
  user_outlined: UserOutlined,
  user_settings_filled: UserSettingsFilled,
  user_settings_outlined: UserSettingsOutlined,
  verified_filled: VerifiedFilled,
  verified_outlined: VerifiedOutlined,
  video_camera_filled: VideoCameraFilled,
  video_camera_off_filled: VideoCameraOffFilled,
  video_camera_off_outlined: VideoCameraOffOutlined,
  video_camera_outlined: VideoCameraOutlined,
  video_gallery_filled: VideoGalleryFilled,
  video_gallery_outlined: VideoGalleryOutlined,
  view_agenda_filled: ViewAgendaFilled,
  view_agenda_outlined: ViewAgendaOutlined,
  view_column_filled: ViewColumnFilled,
  view_column_outlined: ViewColumnOutlined,
  view_grid_filled: ViewGridFilled,
  view_grid_outlined: ViewGridOutlined,
  view_kanban_filled: ViewKanbanFilled,
  view_kanban_outlined: ViewKanbanOutlined,
  view_module_filled: ViewModuleFilled,
  view_module_outlined: ViewModuleOutlined,
  view_timeline_filled: ViewTimelineFilled,
  view_timeline_outlined: ViewTimelineOutlined,
  visibility_hide_filled: VisibilityHideFilled,
  visibility_hide_outlined: VisibilityHideOutlined,
  visibility_show_filled: VisibilityShowFilled,
  visibility_show_outlined: VisibilityShowOutlined,
  volume_down_filled: VolumeDownFilled,
  volume_down_outlined: VolumeDownOutlined,
  volume_mute_filled: VolumeMuteFilled,
  volume_mute_outlined: VolumeMuteOutlined,
  volume_off_filled: VolumeOffFilled,
  volume_off_outlined: VolumeOffOutlined,
  volume_up_filled: VolumeUpFilled,
  volume_up_outlined: VolumeUpOutlined,
  warning_filled: WarningFilled,
  warning_outlined: WarningOutlined,
  water_alt: WaterAlt,
  water: Water,
  waterdrop_filled: WaterdropFilled,
  waterdrop_outlined: WaterdropOutlined,
  wifi_off: WifiOff,
  wifi: Wifi,
  windmill: Windmill,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
};
