export const HEADER_DESKTOP_BREAKPOINT_PX = 1024;

export const HEADER_MAIN_HEIGHT_PX = 80;
export const HEADER_MAIN_HEIGHT_COMPACT_PX = 64;

export const HEADER_MIN_INTERACTIVE_TARGET_PX = 24;

export const HEADER_MOBILE_SEARCH_TRANSITION_MS = 150;

export const HEADER_DEFAULT_NAV_ARIA_LABEL = "Navigation principale";
export const HEADER_DEFAULT_BREADCRUMBS_ARIA_LABEL = "Fil d'Ariane";
