name: Cleanup Storybook Preview

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Sanitize branch name (match deploy)
        id: vars
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          SLUG="${BRANCH_NAME##*/}"         # same as GITHUB_REF##*/
          SLUG="${SLUG//\//}"               # remove any remaining slashes
          echo "slug=$SLUG" >> $GITHUB_OUTPUT

      - name: Delete preview folder
        run: |
          rm -rf preview/${{ steps.vars.outputs.slug }}
          git rm -rf preview/${{ steps.vars.outputs.slug }} || echo "Nothing to delete"
          git commit -m "chore: remove preview for ${{ steps.vars.outputs.slug }}" || echo "Nothing to commit"
          git push
